# Generated by Django 6.0.6 on 2026-06-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_remove_menu_description_menu_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='booking_date',
        ),
    ]
